services:
    redis:
      image: redis:latest
      ports:
        - 6480:6379
      volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    nginx:
      hostname: nginx-knigochei-dev
      image: nginx:latest
      container_name: knigochei_nginx_dev
      ports:
        - 15511:80
      volumes:
        - ./:/var/www
        - ./tmp/nginx/logs:/var/log/nginx
        - ./_docker/local/nginx/conf_local.d:/etc/nginx/conf.d
      depends_on:
        - app
      links:
        - app
      working_dir: /var/www
    app:
      hostname: knigochei.dev
      build:
        context: .
        dockerfile: _docker/local/app/Dockerfile
        args:
          XDEBUG: true
      container_name: knigochei_app_dev
      volumes:
        - ./:/var/www
      working_dir: /var/www
    kafka:
      image: apache/kafka:3.7.0
      container_name: kafka
      command: >
        /bin/sh -c "
        KAFKA_CLUSTER_ID=$$(/opt/kafka/bin/kafka-storage.sh random-uuid);
        /opt/kafka/bin/kafka-storage.sh format -t $$KAFKA_CLUSTER_ID -c /opt/kafka/config/kraft/server.properties;
        exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
        "
      environment:
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      ports:
        - "9092:9092"
      volumes:
        - ./kafka-data:/tmp/kraft-combined-logs
      networks:
        - backend
    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      ports:
        - "8080:8080"
      environment:
        DYNAMIC_CONFIG_ENABLED: "true"
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      depends_on:
        - kafka
networks:
  backend:
    driver: bridge

#    db:
#      build:
#        context: .
#        dockerfile: _docker/local/db/Dockerfile
#      container_name: db_dev
#      volumes:
#        - ./tmp/postgresql_db_16:/var/lib/postgresql/data
#      environment:
#        POSTGRES_PASSWORD: postgres
#      ports:
#        - 15512:5432
